=== Alinoss2910/LMGSI_UD4/Cliente/clientes.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT clientes (sede)+>
<!ATTLIST clientes
  xmlns CDATA #FIXED ''>

<!ELEMENT sede (direccion,empleado,fecha,descripcion?,cliente+)>
<!ATTLIST sede
  xmlns CDATA #FIXED ''
  codigo CDATA #REQUIRED>

<!ELEMENT direccion (#PCDATA)>
<!ATTLIST direccion
  xmlns CDATA #FIXED ''>

<!ELEMENT empleado (#PCDATA)>
<!ATTLIST empleado
  xmlns CDATA #FIXED ''>

<!ELEMENT fecha (#PCDATA)>
<!ATTLIST fecha
  xmlns CDATA #FIXED ''>

<!ELEMENT descripcion (#PCDATA)>
<!ATTLIST descripcion
  xmlns CDATA #FIXED ''>

<!ELEMENT cliente (numero,coste,resumen,plazo)>
<!ATTLIST cliente
  xmlns CDATA #FIXED ''
  codigo CDATA #REQUIRED>

<!ELEMENT numero (#PCDATA)>
<!ATTLIST numero
  xmlns CDATA #FIXED ''>

<!ELEMENT coste (#PCDATA)>
<!ATTLIST coste
  xmlns CDATA #FIXED ''>

<!ELEMENT resumen (#PCDATA)>
<!ATTLIST resumen
  xmlns CDATA #FIXED ''>

<!ELEMENT plazo (#PCDATA)>
<!ATTLIST plazo
  xmlns CDATA #FIXED ''>

=== Alinoss2910/LMGSI_UD4/ClienteV2/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes SYSTEM "clientes.dtd">
<clientes>
    <sede codigo="16816516581">
        <direccion>C/alameda</direccion>
        <empleado>Pepe Cazada</empleado>
        <fecha>13-06-2015</fecha>
        <descripcion>Vender casa</descripcion>
        <cliente codigo="15135">
            <numero>2</numero>
            <coste>150000</coste>
            <resumen>Cambio de papeles</resumen>
            <plazo>10</plazo>
        </cliente>
        <cliente codigo="16851684">
            <numero>1</numero>
            <coste>150000</coste>
            <resumen>Comprar</resumen>
            <plazo>8</plazo>
        </cliente>
    </sede>
    <sede codigo="16584651">
        <direccion>C/ Anafera</direccion>
        <empleado>Coby Brian</empleado>
        <fecha>10-08-2015</fecha>
        <cliente codigo="146894168">
            <numero>45</numero>
            <coste>5000000</coste>
            <resumen>Vender</resumen>
            <plazo>5</plazo>
        </cliente>
        <cliente codigo="8974563211">
            <numero>1</numero>
            <coste>160000</coste>
            <resumen>Comprar</resumen>
            <plazo>9</plazo>
        </cliente>
    </sede>
</clientes>
