=== Alinoss2910/LMGSI_UD4/PracticasCFGS/practicas.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT alumnos (alumno)+>
<!ATTLIST alumnos
  xmlns CDATA #FIXED ''>

<!ELEMENT alumno (nif,resultado,(mac|(obsevaciones,ip)))>
<!ATTLIST alumno
  xmlns CDATA #FIXED ''>

<!ELEMENT nif (#PCDATA)>
<!ATTLIST nif
  xmlns CDATA #FIXED ''>

<!ELEMENT resultado (#PCDATA)>
<!ATTLIST resultado
  xmlns CDATA #FIXED ''>

<!ELEMENT mac (#PCDATA)>
<!ATTLIST mac
  xmlns CDATA #FIXED ''>

<!ELEMENT obsevaciones EMPTY>
<!ATTLIST obsevaciones
  xmlns CDATA #FIXED ''>

<!ELEMENT ip (#PCDATA)>
<!ATTLIST ip
  xmlns CDATA #FIXED ''>

=== Alinoss2910/LMGSI_UD4/PracticasCFGS/practicas.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE alumnos SYSTEM "practicas.dtd">
<alumnos>
    <alumno>
        <nif>32912867M</nif>
        <resultado>Apto</resultado>
        <obsevaciones></obsevaciones>
        <ip>10.0.0.2</ip>
    </alumno>
    <alumno>
        <nif>11111111A</nif>
        <resultado>No Apto</resultado>
        <mac>5A:2F:12:FC:08:AC</mac>
    </alumno>
</alumnos>
